In [1]:
import tensorflow as tf

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

string,number, floating

(<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.566999912261963>)

In [2]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

rank2_tensor.shape

TensorShape([2, 2])

# Changing Shape

In [3]:
tensor = tf.ones([1, 2, 3])
tensor1 = tf.reshape(tensor, [2, 3, 1])
tensor2 = tf.zeros([3,2, 4, 5])


# Vector calucation

In [4]:
# Addition
# You can add tensors together with the addition operator

tensor1 = tf.constant([[2,4,3], [5,7,8], [9, 6, 7]])
tensor2 = tf.constant([[3,5,7], [8,3,4], [5, 7, 8]])
sum = tf.add(tensor1, tensor2)
sum

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5,  9, 10],
       [13, 10, 12],
       [14, 13, 15]], dtype=int32)>

In [5]:
#Matrix Multiplication
# In machine learning, matrix multiplication is one of the most common operations.

# Given matrix a, multiply it by 4
matrix1 = tf.constant([[3, 4, -1], [0, 9, 5]])
multiplied = tf.multiply(matrix1, 4)
print(multiplied)

# Given a matrix a and a matrix b, the matrix product is a third matrix c.
matrixA = tf.constant([[3, 7], [4, 9]])
matrixB = tf.constant([[6, 2], [5, 8]])
matrix_product = tf.matmul(matrixA, matrixB)
matrix_product

tf.Tensor(
[[12 16 -4]
 [ 0 36 20]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[53, 62],
       [69, 80]], dtype=int32)>